### ISSUE TITLE
对于RELEASE的下载可有加速办法吗？

### ISSUE THREAD

**Issue by reki-cool** [dbarobin/github#3]
如题，CODE==》RELEASE下载，这个好像不支持，速度极慢！

**Comment by dbarobin** [comment]
> 如题，CODE==》RELEASE 下载，这个好像不支持，速度极慢！

这个就要系统代理或者 Chrome 代理了，我用 Surge 处理的。

**Comment by reki-cool** [comment]
> > 如题，CODE==》RELEASE 下载，这个好像不支持，速度极慢！
> 
> 这个就要系统代理或者 Chrome 代理了，我用 Surge 处理的。

OK，多谢方案提供！
